"""

Django settings for blogproject project.



Generated by 'django-admin startproject' using Django 1.10.6.



For more information on this file, see

https://docs.djangoproject.com/en/1.10/topics/settings/



For the full list of settings and their values, see

https://docs.djangoproject.com/en/1.10/ref/settings/

"""



import os



# Build paths inside the project like this: os.path.join(BASE_DIR, ...)

BASE_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))



# Quick-start development settings - unsuitable for production

# See https://docs.djangoproject.com/en/1.10/howto/deployment/checklist/



# SECURITY WARNING: keep the secret key used in production secret!

SECRET_KEY = 'i3k%m-808v3_)^h7975iw4v&fl5chq41^19j@u+b*vx7dvw*q$'



# SECURITY WARNING: don't run with debug turned on in production!

DEBUG = False



ALLOWED_HOSTS = ['127.0.0.1', 'localhost', '.guoyunfei.online']
#改成ALLOWED_HOSTS=['*'] ##* 表示任意地址允许访问


# Application definition



INSTALLED_APPS = [

    'django.contrib.admin',

    'django.contrib.auth',
    'django.contrib.contenttypes',
    #上面两个用户认证系统的必要配置
    #contenttypes时auth模块的用户权限处理部分依赖的应用

    'django.contrib.sessions',

    'django.contrib.messages',

    'django.contrib.staticfiles',

    'blog',
    #博客应用

    'comments',
    #评论应用
    
    #'users'
    #用户应用
]



MIDDLEWARE = [
    #中间件
    'django.middleware.security.SecurityMiddleware',

    'django.contrib.sessions.middleware.SessionMiddleware',
     #用户处理用户会话。
    'django.middleware.common.CommonMiddleware',

    'django.middleware.csrf.CsrfViewMiddleware',

    'django.contrib.auth.middleware.AuthenticationMiddleware',
    #绑定一个 User 对象到请求中
    'django.contrib.messages.middleware.MessageMiddleware',

    'django.middleware.clickjacking.XFrameOptionsMiddleware',

]



ROOT_URLCONF = 'blogproject.urls'



TEMPLATES = [

    {

        'BACKEND': 'django.template.backends.django.DjangoTemplates',

        'DIRS': [os.path.join(BASE_DIR, 'templates')],
        #dir设置模板的路径
        #BASE_DIR记录的是工程根目录，templates即工程根目录下的模板文件夹

        'APP_DIRS': True,

        'OPTIONS': {

            'context_processors': [

                'django.template.context_processors.debug',

                'django.template.context_processors.request',

                'django.contrib.auth.context_processors.auth',

                'django.contrib.messages.context_processors.messages',

            ],

        },

    },

]



WSGI_APPLICATION = 'blogproject.wsgi.application'



# Database

# https://docs.djangoproject.com/en/1.10/ref/settings/#databases



DATABASES = {

    'default': {

        'ENGINE': 'django.db.backends.sqlite3',

        'NAME': os.path.join(BASE_DIR, 'db.sqlite3'),

    }

}



# Password validation

# https://docs.djangoproject.com/en/1.10/ref/settings/#auth-password-validators



AUTH_PASSWORD_VALIDATORS = [

    {

        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',

    },

    {

        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',

    },

    {

        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',

    },

    {

        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',

    },

]



# Internationalization

# https://docs.djangoproject.com/en/1.10/topics/i18n/


#AUTH_USER_MODEL = 'users.User'
#指定自定义用户模型所在的位置

LANGUAGE_CODE = 'zh-hans'
#语言设置


TIME_ZONE = 'Asia/Shanghai'
#时区设置


USE_I18N = True



USE_L10N = True



USE_TZ = True



# Static files (CSS, JavaScript, Images)

# https://docs.djangoproject.com/en/1.10/howto/static-files/



STATIC_URL = '/static/'
STATIC_ROOT = os.path.join(BASE_DIR, 'static')
#指明了静态文件的收集目录，即项目根目录（BASE_DIR）下的 static 文件夹。